from app.schemas import Aggregation, ReportMetadata, Score, Section


def render_markdown(
    metadata: ReportMetadata,
    score: Score,
    aggregation: Aggregation,
    sections: list[Section],
) -> str:
    lines = [
        f"# {metadata.title}",
        "",
        f"> **{metadata.organization}** · Project **{metadata.project}** · Environment **{metadata.environment}**  ",
        f"> Generated by {metadata.generator} v{metadata.version} on {metadata.generated_at}  ",
        f"> Report type: **{metadata.report_type}** · Audience: **{metadata.audience}**",
        "",
        f"**Score {score.value}/100 · Grade {score.grade} · {score.posture}** — "
        f"{aggregation.actionable_findings} actionable finding(s) across {len(aggregation.module_counts)} module(s).",
        "",
        "---",
        "",
    ]
    for section in sections:
        lines.append(f"## {section.title}")
        lines.append("")
        lines.append(section.body.strip())
        lines.append("")
        lines.append("---")
        lines.append("")
    if lines and lines[-2] == "---":
        lines = lines[:-2]
    return "\n".join(lines).strip() + "\n"
